title: iooikos Blog
author: iooikos-ludo
email: ludovic.saas@iooikos.com
description: Yann is passionate about IT. He is blogging about this stuff here.
show_excerpts: true 
# set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: Yann Tromeur
  tagline: Geek & Poke
  date_format: "%b %-d, %Y"
  style: red
  showNav: true
  showPicker: false

  # generate social links in footer
  social_links:
    twitter: iooikos
    github:  iooikos-yann
    linkedIn: in/yann.tromeur
    rss: rss
 

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: texture

plugins:
  - jekyll-seo-tag
#  - jekyll-feed
